config/routes.rb
Rails.application.routes.draw do
  get '/contact_us', to: "contact#contact_us"
  devise_for :users
  resources :articles
  resources :posts
  resources :topics
  resources :courses
  resources :students
  # root "static#index"
  # get "/time", to: "time#index"
  post "/message", to: "message#write"
  get "/message", to: "message#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
end

app/models/topic.rb
class Topic < ApplicationRecord
	belongs_to :student
	belongs_to :course
	has_many :posts
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: %i[ show edit update destroy ]

  # GET /topics or /topics.json
  def index
    @topics = Topic.all
  end

  # GET /topics/1 or /topics/1.json
  def show
  end

  # GET /topics/new
  def new
    @topic = Topic.new
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics or /topics.json
  def create
    @topic = Topic.new(topic_params)

    respond_to do |format|
      if @topic.save
        format.html { redirect_to topic_url(@topic), notice: "Topic was successfully created." }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1 or /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to topic_url(@topic), notice: "Topic was successfully updated." }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1 or /topics/1.json
  def destroy
    @topic.destroy

    respond_to do |format|
      format.html { redirect_to topics_url, notice: "Topic was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def topic_params
      params.require(:topic).permit(:title, :student_id, :course_id)
    end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<%= form_with(model: topic) do |form| %>
  <% if topic.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
        <% topic.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :student_id, style: "display: block" %>
    <%= form.text_field :student_id %>
  </div>

  <div>
    <%= form.label :course_id, style: "display: block" %>
    <%= form.text_field :course_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/topics/_topic.html.erb
<div id="<%= dom_id topic %>">
  <p>
    <strong>Title:</strong>
    <%= topic.title %>
  </p>

  <p>
    <strong>Student:</strong>
    <%= topic.student_id %>
  </p>

  <p>
    <strong>Course:</strong>
    <%= topic.course_id %>
  </p>

</div>

app/views/topics/edit.html.erb
<h1>Editing topic</h1>

<%= render "form", topic: @topic %>

<br>

<div>
  <%= link_to "Show this topic", @topic %> |
  <%= link_to "Back to topics", topics_path %>
</div>

app/views/topics/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Topics</h1>

<div id="topics">
  <% @topics.each do |topic| %>
    <%= render topic %>
    <p>
      <%= link_to "Show this topic", topic %>
    </p>
  <% end %>
</div>

<%= link_to "New topic", new_topic_path %>

app/views/topics/new.html.erb
<h1>New topic</h1>

<%= render "form", topic: @topic %>

<br>

<div>
  <%= link_to "Back to topics", topics_path %>
</div>

app/views/topics/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @topic %>

<div>
  <%= link_to "Edit this topic", edit_topic_path(@topic) %> |
  <%= link_to "Back to topics", topics_path %>

  <%= button_to "Destroy this topic", @topic, method: :delete %>
</div>